Repository aws-samples/awsome-distributed-training, pull requests merged in 2023-11, with the labels that each got.

#32 Fix mpt example
  3.test_cases/3.MPT/0.llm-foundry.Dockerfile
  3.test_cases/3.MPT/2.train-mpt-manual-distributed.sbatch
  3.test_cases/3.MPT/Makefile
Labels: bug

#35 Switch path
  3.test_cases/3.MPT/2.train-mpt-manual-distributed.sbatch
Labels: hotfix

#36 EFA cheatsheet
  1.architectures/efa-cheatsheet.md
Labels: documentation

#42 add tensorflow example
  3.test_cases/7.tensorflow-distributed/0.tensorflow.Dockerfile
  3.test_cases/7.tensorflow-distributed/1.run-training.sbatch
  3.test_cases/7.tensorflow-distributed/Makefile
  3.test_cases/7.tensorflow-distributed/README.md
  3.test_cases/7.tensorflow-distributed/src/worker.py
Labels: enhancement

#45 Update README.md
  README.md
Labels: documentation

#49 revise neuronx-nemo-megatron example
  3.test_cases/8.neuronx-nemo-megatron/1.convert-weight.sbatch
  3.test_cases/8.neuronx-nemo-megatron/1.setup-venv.sh
  3.test_cases/8.neuronx-nemo-megatron/2.setup-neuronx-nemo-megatron.sh
  3.test_cases/8.neuronx-nemo-megatron/2.tokenize.sh
  3.test_cases/8.neuronx-nemo-megatron/3.convert-weight.sbatch
  3.test_cases/8.neuronx-nemo-megatron/3.precompile-model.sh
  3.test_cases/8.neuronx-nemo-megatron/4.pretrain-model.sh
  3.test_cases/8.neuronx-nemo-megatron/4.tokenize.sbatch
  3.test_cases/8.neuronx-nemo-megatron/5.precompile-model.sh
  3.test_cases/8.neuronx-nemo-megatron/6.pretrain-model.sh
  3.test_cases/8.neuronx-nemo-megatron/README.md
Labels: enhancement
