Repository aws-samples/awsome-distributed-training, pull requests merged in 2024-08, with the labels that each got.

#398 Update Llama3 NxD test case
  3.test_cases/neuronx-distributed/llama3/slurm/README.md
Labels: documentation

#395 add nccom-tests micro benchmark
  micro-benchmarks/nccom-tests/README.md
  micro-benchmarks/nccom-tests/slurm/README.md
  micro-benchmarks/nccom-tests/slurm/nccom-tests.sbatch
Labels: enhancement

#401 Update 1.conda-train.sbatch
  3.test_cases/16.pytorch-cpu-ddp/slurm/1.conda-train.sbatch
Labels: bug

#406 Add a guide for g5/g6 instance to efa-cheatsheet.md
  1.architectures/efa-cheatsheet.md
Labels: documentation

#407 update TORCHRUN_ARGS to be able to auto-resume
  3.test_cases/16.pytorch-cpu-ddp/slurm/1.conda-train.sbatch
  3.test_cases/16.pytorch-cpu-ddp/slurm/3.container-train.sbatch
Labels: bug

#385 FSDP: Mistral(mathstral) sbatch file - MISTRAL MODEL SUPPORT
  3.test_cases/10.FSDP/2.distributed-training-mixtral.sbatch
  3.test_cases/10.FSDP/3.distributed-training-mistral-mathstral.sbatch
  3.test_cases/10.FSDP/README.md
Labels: New model

#384 FSDP: Add mistral model type support
  3.test_cases/10.FSDP/model_utils/train_utils.py
Labels: New model
